# Generated by Django 5.2 on 2025-04-03 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Otwarty'), ('IN_PROGRESS', 'W trakcie...'), ('CLOSED', 'Zamknięty')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Niski'), ('MEDIUM', 'Średni'), ('HIGH', 'Wysoki'), ('URGENT', 'Najwyższy')], default='LOW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('of_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.department')),
            ],
        ),
    ]
