# Generated by Django 5.2 on 2025-06-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE_FAILURE', 'Problem ze sprzętem'), ('SOFTWARE_FAILURE', 'Problem z oprogramowaniem'), ('DEVICE_NEEDS', 'Zapotrzebowanie na sprzęt')], default=None, max_length=32, verbose_name='Kategoria zgłoszenia'),
        ),
    ]
